### ISSUE TITLE
Removal from PyPI

### ISSUE THREAD

**Issue by anmorrissey** [yuhangwang/allo#1]
Hello. I have been trying to contact you through various means as your email is not listed anywhere. You have an empty project on PyPI for this repo with the name Allo. I have a finished software that we are getting ready for publication with the same name. Is it possible that you could delete this from PyPI so I can use this name? I have opened an issue with PyPI as well to get it deleted on the basis that it is abandoned but they appear to take a very long time to actually transfer names. I would really appreciate your help. Thank you.

**Comment by yuhangwang** [comment]
I have removed the allo package from PyPI. You should be able to register your package under allo now.
